// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/sqkam/goproxy/ioc"
	"github.com/sqkam/goproxy/pkg/proxy"
)

// Injectors from wire.go:

func InitProxyServer() proxy.Service {
	proxyConfig := ioc.InitConfig()
	service := ioc.InitProxyServer(proxyConfig)
	return service
}
